language: bash
services:
  - mysql

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

  - mysql -uroot -e 'create database my_empty_db;'
  - mysql -uroot -e 'create database my_full_db;'
  - mysql -uroot -e 'Use my_full_db; CREATE TABLE test (b1 LONGTEXT, b2 LONGTEXT, b3 LONGTEXT, b4 LONGTEXT, b5 LONGTEXT, b6 LONGTEXT, b7 LONGTEXT, b8 LONGTEXT, b9 LONGTEXT, ba LONGTEXT, bb LONGTEXT, bc LONGTEXT, bd LONGTEXT, be LONGTEXT, bf LONGTEXT;'
  - for (( i=1; i < 5000; i++ )); do mysql -uroot -e 'use my_full_db; INSERT INTO test VALUES("10000000000", "20000000000", "30000000000", "40000000000", "50000000000", "60000000000", "70000000000", "80000000000", "90000000000", "A00000000000", "B0000000000", "C0000000000", "D0000000000", "E00000000000", "F0000000000");'; done;


sudo: required
#install:
#      - sudo apt-get -qq update
#      - sudo apt-get -qq install git devscripts shunit2

script:
  - shellcheck --shell=sh bin/mysqldump-secure
  - shellcheck --shell=sh bin/create-keypair.sh
  - shellcheck --shell=sh bin/decrypt.sh
  - shellcheck --shell=sh bin/encrypt.sh
  - shellcheck --shell=sh --exclude=SC2034,SC2148 etc/mysqldump-secure.conf

  # install mysqldump-secure
  - ./configure
  - make
  - sudo make install
  - echo '[client]' | sudo tee /etc/mysqldump-secure.cnf
  - echo 'host = localhost' | sudo tee --append /etc/mysqldump-secure.cnf
  - echo 'user = root' | sudo tee --append /etc/mysqldump-secure.cnf
  - echo 'password = ' | sudo tee --append /etc/mysqldump-secure.cnf

  - sudo mysqldump-secure --test
  - sudo mysqldump-secure

