language: bash
services:
  - mysql

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

  - mysql -uroot -e 'create database my_empty_db;'
  - mysql -uroot -e 'create database my_full_db;'
  - mysql -uroot -e 'Use my_full_db; CREATE TABLE test (b1 BLOB, b2 BLOB, b3 BLOB, b4 BLOB, b5 BLOB, b6 BLOB, b7 BLOB, b8 BLOB, b9 BLOB, b10 BLOB);'
  - for (( i=1; i < 5000; i++ )); do mysql -uroot -e 'use my_full_db; INSERT INTO test VALUES("1", "2", "3", "4", "5", "6", "7", "8", "9", "10");'; done;


sudo: required
#install:
#      - sudo apt-get -qq update
#      - sudo apt-get -qq install git devscripts shunit2

script:
  - shellcheck --shell=sh bin/mysqldump-secure
  - shellcheck --shell=sh bin/create-keypair.sh
  - shellcheck --shell=sh bin/decrypt.sh
  - shellcheck --shell=sh bin/encrypt.sh
  - shellcheck --shell=sh --exclude=SC2034,SC2148 etc/mysqldump-secure.conf

  # install mysqldump-secure
  - ./configure
  - make
  - sudo make install
  - echo '[client]' | sudo tee /etc/mysqldump-secure.cnf
  - echo 'host = localhost' | sudo tee --append /etc/mysqldump-secure.cnf
  - echo 'user = root' | sudo tee --append /etc/mysqldump-secure.cnf
  - echo 'password = ' | sudo tee --append /etc/mysqldump-secure.cnf

  - sudo mysqldump-secure --test
  - sudo mysqldump-secure

