language: bash
services:
  - mysql

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

  - mysql -uroot -e 'create database myapp_test;'
  - mysql -uroot -e 'Use myapp_test;'
#sudo: required
#install:
#      - sudo apt-get -qq update
#      - sudo apt-get -qq install git devscripts shunit2

script:
  - shellcheck --shell=sh bin/mysqldump-secure
  - shellcheck --shell=sh bin/create-keypair.sh
  - shellcheck --shell=sh bin/decrypt.sh
  - shellcheck --shell=sh bin/encrypt.sh
  - shellcheck --shell=sh --exclude=SC2034,SC2148 etc/mysqldump-secure.conf

test:
  - ./configure
  - make
  - make install

