dist: trusty
sudo: required



language: bash



addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6



services:
  - mysql



before_install:
  # Install 'shellcheck' and 'tmpreaper'
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck tmpreaper



before_script:

  # -------------------- MySQL --------------------


  # Installs mysqldump-secure and MySQL as with as master and a slave server
  - ./.travis/00-install.sh
  - sleep 10


  - sudo mysql --ssl-ca=/opt/mysqldump-secure/tests/etc/mysql.ca.pem --user=root --host=127.0.0.1 --port=13306 -e "status;"
  - sudo mysql --ssl-ca=/opt/mysqldump-secure/tests/etc/mysql.ca.pem --user=root --host=127.0.0.1 --port=13307 -e "status;"

  # 6. Show config
  # - sudo cat /etc/mysqldump-secure.conf


script:


  # --------------------------------------------------------------------------------
  #
  # SOURCE CODE LINTING
  #
  # --------------------------------------------------------------------------------

  # Shellcheck
  - shellcheck --shell=sh bin/mysqldump-secure
  - shellcheck --shell=sh bin/create-keypair.sh
  - shellcheck --shell=sh bin/decrypt.sh
  - shellcheck --shell=sh bin/encrypt.sh
  - shellcheck --shell=sh --exclude=SC2034,SC2148 etc/mysqldump-secure.conf


  # --------------------------------------------------------------------------------
  #
  # Checks
  #
  # --------------------------------------------------------------------------------

  - ./.travis/01-check_normal-operation.sh
  - ./.travis/02-check_output_dirs.sh
  - ./.travis/03-check_connection_settings.sh
  - ./.travis/04-check_mysqldump_settings.sh
  - ./.travis/05-check_consistency_settings.sh
  - ./.travis/06-check_logging.sh
  - ./.travis/07-check_compression.sh
  - ./.travis/08-check_encryption.sh
  - ./.travis/09-check_deletion.sh
  - ./.travis/10-check_nagios_log.sh
  - ./.travis/11-check_misc_settings.sh


  # TODO:
  #  * Duplicate files testing!!!
  #  * Connection checking (host not found, access denied, etc)
  #  * master/slave tests
  #  * nagios check




  # --------------------------------------------------------------------------------
  #
  # Show info
  #
  # --------------------------------------------------------------------------------

  # Contents of dump folder
  #- sudo ls -la /var/mysqldump-secure
